language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t s1dequest/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true s1dequest/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-629115610323"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
